### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by davidandreoletti** [resurrecting-open-source-projects/dcfldd#22]
Hi,

I am very interested in using dcdldd on macOS and Linux.
Homebrew distributes the ["unrestricted version"](https://formulae.brew.sh/formula/dcfldd) yet yours is better feature wise.

Do you plan to distribute it over homebrew (Linux + Mac) ?

Regards,

David

**Comment by davidpolverari** [comment]
Hi @davidandreoletti!

> I am very interested in using dcdldd on macOS and Linux. Homebrew distributes the ["unrestricted version"](https://formulae.brew.sh/formula/dcfldd) yet yours is better feature wise.

Thanks for your interest in dcfldd! The version in this repository is not "restricted" in any way. We are maintaining dcfldd after the original author stopped maintaining it. The version in Homebrew is an old version of dcfldd.

> 
> Do you plan to distribute it over homebrew (Linux + Mac) ?
> 
We are the maintainers of dcfldd. Usually, the work you are referring to is performed by distributions and/or package manager communities (like Homebrew). Our version already can be found packaged on several Linux distributions, as can be seen in [repology](https://repology.org/project/dcfldd/versions).

As I sometimes need to use dcfldd on some Macs for work, I have contributed changes for the MacPorts dcfldd port, as it is the package manager I use on that platform, and I am not an user of Homebrew. But you could help update the dcfldd Homebrew formula yourself. I have listed some links below that might help you getting started with it:

- https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
- https://docs.brew.sh/Formula-Cookbook
- https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md

When you changes get merged, you will be able to install dcfldd using homebrew. I hope this helps you getting dcfldd packaged in Homebrew!

Regards,

David

**Comment by davidandreoletti** [comment]
Thank you for your thoughtful reply.

Turns out, I really needed on hashing on the fly but did not have enough time to create a home brew package (yet contributed to pre-existing ones)

So, I implemented hashing on the fly + progress bar with a posix shell script (dd+pipe+pv+sha256sum).

**Comment by PeterSuh-Q3** [comment]
I found this repo through this link.

https://ports.macports.org/port/dcfldd/

Like homebrew, port also helps install packages on MacOS.

Instead, port must be pre-installed with the dmg appropriate for each MacOS version.

The installation command is as follows.

sudo port install dcfldd

The location of packages usually installed through homebrew is

I know it as /usr/local/bin.

In the case of port

Proceed with installation in /opt/local/bin.
