### ISSUE TITLE
Pull request welcome?: Make CI cover modern compilers and work with strict `-std=c99`

### ISSUE THREAD

**Issue by hartwork** [resurrecting-open-source-projects/dcfldd#25]
Hi!

The CI does not cover modern compilers like GCC 13 and Clang 18 and I would add that and make `-std=c99` work — currently needs `-std=gnu99` apparently — if there is general interest and a promise of review. How do you feel about that?

Best, Sebastian

**Comment by davidpolverari** [comment]
Hi, @hartwork!

I think it would be an interesting work, especially being able to build using clang cleanly, although I can't promise reviewing it if it involves large(ish) changes. Do you have an estimate to the work involved? I don't know the amount of GCC extensions (if any) the codebase uses. What do you think about it, @eribertomota?

**Comment by hartwork** [comment]
> Hi, @hartwork!
> 
> I think it would be an interesting work, especially being able to build using clang cleanly,

@davidpolverari cool!

> although I can't promise reviewing it if it involves large(ish) changes.

It would be small clean-cut commits to ease review, smaller C fixes and some YAML changes for CI.

> Do you have an estimate to the work involved?

I don't expect too much, and I'll package it in a way that eases review and will not cover all things possible but a first package to give you a taste and then we can do more if you liked the first one. E.g. adding `-Werror` would likely be a target for CI in a later round, not the first.

> I don't know the amount of GCC extensions (if any) the codebase uses. What do you think about it, @eribertomota?
