### ISSUE TITLE
dcfldd write only to maximum 2 output files

### ISSUE THREAD

**Issue by Rahul-Ravichandran** [resurrecting-open-source-projects/dcfldd#9]
Hi,
I tried dcfldd if=somthing.img of=/dev/sda of=/dev/sdb of=/dev/sdc

But it only writes to 2 of them and does not return any error. Please help. 
My main goal is to write to multiple Rpi at the same time (around 10)

**Comment by davidpolverari** [comment]
Hi, @Rahul-Ravichandran.

I couldn't repro this issue. I was able to write to four output files at once with no problems. Maybe a media problem?
I'm closing the issue, as there is no way to reproduce the issue with the information provided, but feel free to reopen it if you can provide further information about it (the way you performed the tests, the kind of media involved, etc).

Regards,
David.
